Style & Invitation Link Page
zengqiangHe/capstone-project pull request #20
Opened 2022-05-17 06:43 UTC by zengqiangHe

Hi there, 
with this PR I have:

- created a invitation link page
- add two buttons to copy the link (one on the home page, another on the link page)
- styled the app

Thanks for reviewing my code!

2022-05-17 12:29 UTC, anitaschiller requested changes
Hi,
I left you some comments. Let me take another look when your project runs again :)

2022-05-17 12:29 UTC, anitaschiller commented on client/src/components/eventCard/EventCard.spec.js
> +// });
I think the test needs to be revised 😉

2022-05-17 12:29 UTC, anitaschiller commented on client/src/components/eventCard/EventCard.jsx
> +    else if (bockCount === 1) setConfirmedText(eventDetail.votes[1].name + ' hat Bock.');
It was unfortunately not possible for me to see the working version since your deployment seems broken and when I run `npm run dev` the app doesn't come beyond "loading".

However I was wondering why you would want to display the second person in your votes array when the bockCount is 1? Shouldn't it be:
```suggestion
    else if (bockCount === 1) setConfirmedText(eventDetail.votes[0].name + ' hat Bock.');
```
?

2022-05-17 12:29 UTC, anitaschiller commented on client/src/pages/Create.jsx
> +          <Span>Titel:</Span>
A label-tag instead of the span would semantically be correct here. Same counts for the other spans in your form.

2022-05-17 12:29 UTC, anitaschiller commented on client/src/pages/EditEventPage.jsx
> +    updateEvent({ title, text, date, time, location, _id: id, votes: event.votes }, id);
Why do you need the `id` twice? :)

2022-05-17 12:29 UTC, anitaschiller commented on client/src/pages/EditEventPage.jsx
> +const Textarea = styled.textarea`
Since the styled-component `Textarea` is the same as in your Create.jsx, you could extract the styled-component to a separate file and reuse it. DRY (don't repeat yourself) 😊. The same applies to the other styled-components in this file.

2022-05-17 12:29 UTC, anitaschiller commented on client/src/pages/InvitationLink.jsx
> +      {/* {isLinkCopied ? <StyledMessage>Link kopiert!</StyledMessage> : ''} */}
Can be deleted!

2022-05-17 12:29 UTC, anitaschiller commented on server/routes/api.js
> +console.log(isConfirmed)
Can be deleted!

2022-05-19 09:28 UTC, zengqiangHe commented on client/src/App.js
> +      .catch((error) => {});
Done

2022-05-19 09:29 UTC, zengqiangHe commented on client/src/App.js
>        .catch((error) => {});
Done

2022-05-19 09:59 UTC, zengqiangHe commented on client/src/App.js
> +const Wrapper = styled.li``;
Done

2022-05-19 10:02 UTC, zengqiangHe commented on client/src/App.js
> +  let voteURL = ' ';
Done

2022-05-19 10:03 UTC, zengqiangHe commented on client/src/App.js
>    }
DONE

2022-05-19 10:03 UTC, zengqiangHe commented on client/src/App.js
>      event.id = Math.random().toString();
Yes.

2022-05-19 10:04 UTC, zengqiangHe commented on client/src/pages/InvitationLink.jsx
> +export default function InvitationLink() {
I don't understand this question, could you take a look of my app, it runs now :P

2022-05-19 10:05 UTC, zengqiangHe commented on client/src/pages/InvitationLink.jsx
> +//   }
Done

2022-05-19 10:05 UTC, zengqiangHe commented on client/src/App.js
> +        {/* diplayLinkCopiedMessage={diplayLinkCopiedMessage} */}
Done

2022-05-19 10:06 UTC, zengqiangHe commented on client/src/components/eventCard/EventCard.spec.js
> +// });
Of course! :P

2022-05-19 10:06 UTC, zengqiangHe commented on client/src/components/eventCard/EventCard.jsx
> +    else if (bockCount === 1) setConfirmedText(eventDetail.votes[1].name + ' hat Bock.');
I've changed it.

2022-05-19 10:07 UTC, zengqiangHe commented on client/src/pages/EditEventPage.jsx
> +    updateEvent({ title, text, date, time, location, _id: id, votes: event.votes }, id);
it doesn't work, if I delete it.

2022-05-19 10:22 UTC, merged